# Generated by Django 5.0.3 on 2024-03-21 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="importangt",
            new_name="important",
        ),
    ]
