# Generated by Django 5.0.3 on 2024-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_rename_importangt_todo_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
